### ISSUE TITLE
v1 bug: ( Cannot use cli.StringFlag (type cli.StringFlag) as type cli.Flag )

### ISSUE THREAD

**Issue by ImJerryChan** [urfave/cli#1010]
Hello, it's my first time to use this module. I have a question about manual v1.
https://github.com/urfave/cli/blob/master/docs/v1/manual.md#placeholder-values
I see the manual tell us to change type cli.StringFlag as cli.Flag(An interface type), but when I compile the code below, it will raise an error
```
app.Flags = []cli.Flag{
    cli.StringFlag{  // raise an error "Cannot use cli.StringFlag (type cli.StringFlag) as type cli.Flag"
      Name:  "config, c",
      Usage: "Load configuration from `FILE`",
    },
    &cli.StringFlag{  // OK
      Name:  "config, c",
      Usage: "Load configuration from `FILE`",
    },
  }
```
When I finish compiling with my solution, I haven't seen the result in help output like:`--config FILE, -c FILE   Load configuration from FILE`，does the document need to be updated? 

I use `go get -t -v github.com/urfave/cli` to download this module, and my go version is `go1.13.4 linux/amd64`

Can you point out my mistake?
thank you.

**Comment by lynncyrin** [comment]
@ImJerryChan

The issue you are having is caused by using the `v1` manual with `v2` of the library. Please do either of the following things:

- look through this issue https://github.com/urfave/cli/issues/928 to figure out how to pin v1, because the error you are receiving is from trying to run v1 code with v2 of the package
- look through this issue https://github.com/urfave/cli/issues/921 for examples of how to upgrade to v2, because the error you are getting is coming from v2
