### ISSUE TITLE
Move man page compatibility to separate package

### ISSUE THREAD

**Issue by oleorhagen** [urfave/cli#1055]
## What problem does this solve?

We have currently run into an issue where 30% of our binary size is the `urfave/cli` library. With the latest release `v2` it it 50%, which for us is not going to fly.

- Add a minimal version of the cli, using conditional compilation maybe?

## Solution description

Add a `minimal` build flag which does not include all the external dependencies like `md2man` etc, and simply contains the 'core' functionality of the library.

**Comment by asahasrabuddhe** [comment]
This is an interesting observation. I think that we could look at making the library `modular` so that it is possible for the users to import certain modules that they want to use and ignore the others. This would considerably help in keeping the size down.

Having said that, I think this won't be possible for the v2.

But, I am glad to share with you that we are currently working on v3. I think I will add this to the list of things that we want to work on. Hopefully, very soon, you should be looking at a lean version of this library.

Thanks!

**Comment by lynncyrin** [comment]
I think if nothing else, it would be a good idea to add some stats about binary size to CI. We can do that now, and look at reducing it for V3.

**Comment by dearchap** [comment]
@meatballhat i believe we have builds which doesn't include docs

**Comment by dearchap** [comment]
Will consider for v3 release
