### ISSUE TITLE
v2 bug: Sub commands call "HandleExitCoder"

### ISSUE THREAD

**Issue by Nokel81** [urfave/cli#1089]
## my urfave/cli version is

v2.2.0

## Checklist

* [x] Are you running the latest v2 release? The list of releases is [here](https://github.com/urfave/cli/releases).
* [x] Did you check the manual for your release? The v2 manual is [here](https://github.com/urfave/cli/blob/master/docs/v2/manual.md)
* [x] Did you perform a search about this problem? Here's the [Github guide](https://help.github.com/en/github/managing-your-work-on-github/using-search-to-filter-issues-and-pull-requests) about searching.

## Dependency Management

- [x] My project is using go modules.
- [x] My project is using vendoring.
- [ ] My project is automatically downloading the latest version.
- [ ] I am unsure of what my dependency management setup is.

## Describe the bug

If a subcommand's Action function returns an `ExitCoder` error then the code that executes the subcommand calls `HandleExitCoder`. This makes unit testing harder and makes sub commands act differently to `*cli.App`.

## To reproduce

1. Have a sub command return an `ExitCoder`
2. Try and write a unit test that uses the whole cli library to set up the flags correctly.

## Observed behavior

The test exits with the `ExitCoder`'s exit code

## Expected behavior

The `ExitCoder` instance to be returned.

## Additional context

I have looked at the other issues on this subject (from 2017) and it looks like there was previous discussion on this topic. 

There is a work-around, that is to define an identify function on the app itself `ExitErrHandler` field. This is suboptimal because spills testing requirements into the production code itself. It also seems weird that this would be an app wide setting and not a command setting.

Given that the current documentation hints that the user should manually call `HandleExitCoder` from the return value of `*cli.App.Run` it seems strange that a subcommand would call it for you.

**Comment by rliebz** [comment]
This seems to me like the correct behavior. An `ExitCoder` is an interface meant to specifically trigger the behavior for an application to exit with a particular exit code. Returning an `ExitCoder` signals that it should happen, and if it shouldn't happen, an `ExitCoder` shouldn't be returned.

There's a default behavior, the `HandleExitCoder` function, which can be overridden at the `cli.App` level either to change that behavior or to allow for testing. A test could potentially look like this:

```go
func TestMyAppExitCode(t *testing.T) {
  myApp := mypackage.NewProductionApp()

  myApp.ExitErrHandler = func(_ *cli.Context, err error) {
    // Any custom test logic, or assertions
    // Or leave it blank just to avoid the call to os.Exit
  }

  err := myApp.Run([]string{"some", "args"})
  // if (err == ...
```

I wouldn't consider a pattern like that to be spilling test requirements into production code, but I also realize this pattern won't work for every use case.

> It also seems weird that this would be an app wide setting and not a command setting.

I wasn't involved with the original design here, but I think it actually makes more sense as an app-wide setting. Individual commands have individual actions they can run, and each action function can choose whether or not to return an error that implements that interface. The app-wide setting says, if some function, at some point in this app's lifecycle, signals that this app should exit, how does an app exit? It could be a call to `os.Exit`, it could be custom error messaging, it could be a check for a sentinel value, and so on. Or it could be a noop.

>  the current documentation hints that the user should manually call HandleExitCoder from the return value of *cli.App.Run

That doesn't match my mental model of how I thought `HandleExitCoder` is used—if you can point me to where that's implied, I can try to figure out what the intent there was, and potentially change the docs if they are misleading.

**Comment by Nokel81** [comment]
So looking back on the documentation, I got it from a combination of the docs (none of which actually said this). 
- https://pkg.go.dev/github.com/urfave/cli/v2@v2.2.0?tab=doc#HandleExitCoder
- https://pkg.go.dev/github.com/urfave/cli/v2@v2.2.0?tab=doc#App.RunAndExitOnError
- https://pkg.go.dev/github.com/urfave/cli/v2@v2.2.0?tab=doc#Exit

Most specifically the last one.

---

I guess my other concern about that is that an error which doesn't implement `ExitCoder` is just ignored without any warning. It also seems weird that `HandleExitCoder` takes `error` and not `ExitCoder`, because even `MultiError` could be made to implement `ExitCoder`.

**Comment by rliebz** [comment]
Thanks for looking back through the docs. I'll see if I can find a little time to make those more clear.

> I guess my other concern about that is that an error which doesn't implement ExitCoder is just ignored without any warning. 

I think the way interface is designed is a bit confusing here. An error which doesn't implement `ExitCoder` is not ignored; it's just not special cased with a call to `os.Exit`. If an app calls `app.Run` and encounters a non-`ExitCoder`, non-`MultiError`, the error is just returned as the result of `Run`, where application developers have the flexibility to handle it however makes sense.

> It also seems weird that HandleExitCoder takes error and not ExitCoder

The names for these functions are actually more limited than their design. `HandleExitCoder` handles two subcategories of error explicitly, while an `ExitErrHandlerFunc` could be extended to handle any kind of error, if someone wanted.

Imagine a scenario in which you had a sentinel error you wanted to special case. You could extend your app to treat that error with a particular exit code:

```go
app.ExitErrHandler = func(context *cli.Context, err error) {
  // Check for a specific error, then handle it with specific behavior
  if errors.Is(err, somepkg.ErrSomethingBadHappened) {
    os.Exit(2)
  }

  // If we want to support the default behavior as well, we can.
  cli.HandleExitCoder(context, err)
}
```

If any command or subcommand returns `somepkg.ErrSomethingBadHappened`, we'd now explicitly exit with a code of 2. Or any other behavior, it doesn't have to be a call to `os.Exit`. 

 If `ExitErrHandlerFunc`s (including `HandleExitCoder`) accepted an `ExitCoder` instead of an `error`, that kind of design would not be possible. 

> because even MultiError could be made to implement ExitCoder.

I'm guessing here, but I assume from the way the code was written that the intention of supporting `MultiError` is to allowing wrapping multiple errors together without losing the error signaling an exit code. If a `MultiError` were made to implement `ExitCoder` as well, then we don't need to inspect it to get an exit code, because we already have one. They're all interfaces—changing the signature to accept only `ExitCoder` would not prevent the error from being a `MultiError` too.

**Comment by rliebz** [comment]
Found this little nugget while revamping some of the docs—I can see why someone might think they're supposed to call this function themselves:
```go
	// Execute this function to handle ExitErrors. If not provided, HandleExitCoder is provided to
	// function as a default, so this is optional.
	ExitErrHandler ExitErrHandlerFunc
```

**Comment by Nokel81** [comment]
I would have said that the types that implement `MultiError` should also be `ExitCoder` and could do their own inspection for the exit code value.

**Comment by rliebz** [comment]
@Nokel81 I think that's the right approach, but I don't know if making that change is worth changing behavior that users may currently be relying on. Definitely something to consider for v3, though.

**Comment by rliebz** [comment]
I think as far as this issue goes, there isn't actually a bug here, just a confusing interface that's hopefully a little easier to understand now.

I'm going to go ahead and close this now that #1091 is merged, feel free to ping back if you feel like the original issue hasn't been addressed.
