### ISSUE TITLE
q: regenerating help dynamically?

### ISSUE THREAD

**Issue by tgirod** [urfave/cli#1111]
Hi. I'm using `cli/v2` to parse commands that are typed in a REPL loop. In my use case, the list of available commands is dynamic - the user can call a command "load [foobar]" to load a new command.

Everything is falling into place, except for one thing: after loading a command, the new command does not appear in the help text. My guess is, `cli` is generating all help text on startup. Is there way to regenerate the help text?

**Comment by tgirod** [comment]
OK, after messing around a bit I narrowed it down to the `(*App).Setup()` method.

So far, my very crude approach is to vendor and add the following method:

```
// Reset forces a rerun of the Setup() method.
func (a *App) Reset() {
	a.didSetup = false
	a.Setup()
}
```

**Comment by rliebz** [comment]
I had a somewhat similar use case—my application has an optional config file as a command-line argument, which modifies the sub-commands and flags that are valid. Because the `cli.App` is stateful, I actually ended up creating and running multiple `cli.App`s, which worked well enough to let me avoid vendoring the library.

 The `didSetup` was definitely the blocker here—it's designed to prevent a `cli.App` from running more than once, and I'm not 100% sure why that behavior is desirable, or what's stateful in the app other than the flags that have been parsed.

**Comment by tgirod** [comment]
After messing a bit more, I found that my `Reset` method also has to remove the `help` command, because it will be regenerated.

**Comment by rliebz** [comment]
The challenge with that approach is that I'm not sure what all of the steps necessary are to ensure that you get an app that's 100% clean of the stateful things from the first call to `Run`. It might just be the call to `didSetup` and `help`, but there could be a dozen other small things you don't notice until later on.

My recommendation would be that if you're changing the app after it's been run, you probably want a factory function that returns a new `cli.App` with your custom parameters. Call it every time you need a fresh app. This lets you avoid forking, and re-use as much logic as makes sense for your use case.

```go
func NewCustomApp(cfg MyCustomAppCfg) *cli.App {
  // ...
}
```

**Comment by tgirod** [comment]
@rliebz you are right, this is a much cleaner approach! gonna check this out.

**Comment by tgirod** [comment]
FYI: I ended up simply using the `Command.Hidden` property to show/hide commands.
