### ISSUE TITLE
v1 bug: Cannot accept - as program argument

### ISSUE THREAD

**Issue by PMcca** [urfave/cli#1125]
## my urfave/cli version is

1.22.4

## Checklist

* [x ] Are you running the latest v1 release? The list of releases is [here](https://github.com/urfave/cli/releases).
* [x ] Did you check the manual for your release? The v1 manual is [here](https://github.com/urfave/cli/blob/master/docs/v1/manual.md)
* [ ] Did you perform a search about this problem? Here's the [Github guide](https://help.github.com/en/github/managing-your-work-on-github/using-search-to-filter-issues-and-pull-requests) about searching.

## Dependency Management

- [x ] My project is using go modules.
- [ ] My project is using vendoring.
- [ ] My project is automatically downloading the latest version.
- [ ] I am unsure of what my dependency management setup is.

## Describe the bug

CLI is unable to accept arguments starting with "-" e.g. an argument like "-rx--xrwx" would be invalid. Even surrounding the - with "" does not work.

## To reproduce

Run something like "go run x.go "-abc" and it will present the program's default usage info

## Observed behavior

Program's usage info shown

## Expected behavior

Program runs as expected and reads the "-" as an argument (can be referenced in os.Args)

If the issue relates to a specific open source Github repo, please link that repo here.

If you can reproduce this issue with a public CI system, please link a failing build here.

## Want to fix this yourself?

We'd love to have more contributors on this project! If the fix for this bug is easily explained and very small, free free to create a pull request for it. You'll want to base the PR off the `v1` branch, all `v1` bug fix releases will be made from that branch.

## Go version
```go version go1.13 linux/amd64```

## Go env
```GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/uesr/.cache/go-build"
GOENV="/home/user/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/user/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/user/go/src/github.com/PMcca/phmod/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build102747487=/tmp/go-build -gno-record-gcc-switches"```

**Comment by rliebz** [comment]
Thanks for opening an issue!

This is a common problem with CLIs—if you had a flag named `-x`, and you wanted to pass `-x`, how would you do it? We can't safely allow args that look like flags in cases where no such flag exists because then we lose error messages if someone fat fingers `-z` instead of `-x`, and the app silently treats it as an arg.

The common solution to this, which this library also implements, is that anything after `--` is considered an arg, unconditionally. So in the provided example, the correct way to disambiguate would be:

```bash
go run x.go -- -abc
```

**Comment by PMcca** [comment]
Thanks. I thought a way of differentiating would be to surround any arguments with "" or ''. Would a solution like this be possible in the library?

**Comment by rliebz** [comment]
It's an interesting idea, but unfortunately shells like bash or zsh don't make that so simple.

Consider the following program:
```go
package main

import (
	"fmt"
	"os"
)

func main() {
	if len(os.Args) != 3 {
		fmt.Println("Error: Pass two args to compare")
		os.Exit(1)
	}

	fmt.Println(os.Args[1:])

	fmt.Println("args are equal:", os.Args[1] == os.Args[2])
}
```

It's a simple utility that takes two args passed, prints them, then prints whether they are equal. Run it with the following:
```bash
go run foo "foo"
```

And get the following output:

```
[foo foo]
args are equal: true
```

The application doesn't actually receive the quotation marks, and the two args are equal. The reason is because a shell uses quotation marks to determine word boundaries. If for example you wanted to pass a program a single arg containing many spaces, you could do something like this:

```bash
mycmd "super long arg with many spaces"
```

Instead of this:

```bash
mycmd super\ long\ arg\ with\ many\ spaces
```

Or take a variable and prevent it from splitting, for example if a filepath might include a directory called `My Documents` by calling `"$SOMEDIR"` instead of `$SOMEDIR`.

In theory you could get around that by quoting your quotes, or backslash escaping them:
```bash
mycmd \"foo\" '"foo"'
```

But then how would you disambiguate those as args from args that are supposed to have quotes in them? You could pick another pattern, but it starts to get tricky.

People far better at this than I am decided that `--` would be a good enough standard for flagging that everything after should be an arg and not a flag. Most command-line applications I know of use that, so I would advocate for us continuing to stick to that standard.

**Comment by PMcca** [comment]
Ah I see. I didn't realise this was such a long-standing and widespread issue. 
Thanks for your help! Closing
