### ISSUE TITLE
Make options mutually exclusive

### ISSUE THREAD

**Issue by marcofranssen** [urfave/cli#1222]
## mutual exclusive options

Is it possible to make an option required if another option is not provided.

**e.g.**

If I provide `--app-id` `--app-secret` then `--token` is not required.
If I provide `--token`, then `--app-secret` and `--app-id` is not required.

**Comment by dearchap** [comment]
Dont think so. Would be a good feature to have though

**Comment by ebarped** [comment]
would love to see this

**Comment by dearchap** [comment]
@meatballhat I actually begun working on this sometime back but stopped due to all the generated flag changes etc. Do you have any suggestion on what the output of help for a "flag group" would look like. Something like this ? What about defaults, envs etc ? 

[ --foo value --bar value ] | --zz value

**Comment by meatballhat** [comment]
@dearchap there's certainly a lot to consider! I think the help output with `|` separating mutually exclusive values works well. Do the displayed text for defaults or env vars need to change? 🤔
