### ISSUE TITLE
Support aliases in .yml files (altsrc.InitConfigFileInputSourceFunc)

### ISSUE THREAD

**Issue by binwiederhier** [urfave/cli#1394]
## Checklist

* [x] Are you running the latest v2 release? The list of releases is [here](https://github.com/urfave/cli/releases).
* [x] Did you check the manual for your release? The v2 manual is [here](https://github.com/urfave/cli/blob/main/docs/v2/manual.md).
* [ ] Did you perform a search about this feature? Here's the [Github guide](https://help.github.com/en/github/managing-your-work-on-github/using-search-to-filter-issues-and-pull-requests) about searching.

## What problem does this solve?

Thank you for this project. It's fantastic. I've been a long time user and I'm very happy.

I just added the ability to use the `Aliases` in my yml file when loading through `altsrc` (see https://github.com/binwiederhier/ntfy/commit/91594faf288d13bd128067436e11345dc7a9d583#diff-d1253876bc7a1b30f67245948f61e61430af2f3f0bf72780e3c0314a24d152deR43-R50). I was wondering if that was something you'd be interested in adding as a feature. 

If not, I'm alright too and you can close this ticket.

## Solution description

Example:

``` go
altsrc.NewStringFlag(&cli.StringFlag{Name: "listen-http", Aliases: []string{"listen_http", "l"},  ...}),
```

Should be loadable via the .yml file:

``` yaml
# Currently supported:
listen-http: ":80"

# Would also be supported with the suggested change (see Aliases above):
listen_http: ":80"
l: ":80"
```

**Comment by meatballhat** [comment]
@binwiederhier Hello and sorry for the delay! 😭  This looks like a welcome change to me. Are you up for proposing a PR?

**Comment by binwiederhier** [comment]
Sure, I'll give it a shot. No promises :-D

**Comment by ccremer** [comment]
Hi. Just chiming into the discussion, my suggestion/idea is related to having aliases in altsrc.
What I'm currently missing in altsrc, is the ability to have an alternate structure in the alternative source (e.g. YAML) (correct me if I'm missing something).
For example, for CLI flags and Env vars I'd keep a short and user friendly name, e.g. `--namespace` or `--some-flag=true`. Yet in an alternate source, I'd want to have a certain structure. Consider the following YAML:
```yaml
global:
  namespace: my-value
authentication:
  s3:
    some-flag: true
```
It would be great to be able to map the CLI flag `--some-flag` to `authentication.s3.some-flag` in the YAML/JSON, without having it to change the CLI flag to `--authentication.s3.some-flag=true` so that the mapping occurs.

I was thinking along aliases, but maybe a dedicated property in the altsrc Flag variants is better fitting where it could accept a delimited value like `Path: "authentication.s3"` to indicate where the value is located in the structure.

Thoughts?
(Not sure if that is the right issue or if it's better discussed in another issue)
