### ISSUE TITLE
GlobalIsSet always returns false for values specified via EnvVar

### ISSUE THREAD

**Issue by pwaller** [urfave/cli#224]
I instrumented my code with this:

```go
	for _, name := range c.GlobalFlagNames() {
		log.Println(name, c.GlobalString(name), c.GlobalIsSet(name))
	}
```

And I get the output:

```
myvariable myvariablevalue false
```

... when the flag is set to `myvariablevalue` via the environment (through `EnvVar:`).

I want to write a check which aborts if the value has not been specified, which doesn't seem obvious how to achieve.

**Comment by jszwedko** [comment]
Thank you for reporting this -- looking at the code it's going to take a little bit of refactoring due to the way we leverage the stdlib `flag` package for this functionality, but I'll try to fix this soon.

**Comment by paddie** [comment]
Awesome, I was just bitten by this issue.

**Comment by eduser25** [comment]
This is old. Any updates as of a fix for this?

**Comment by meatballhat** [comment]
@eduser25 This issue is still open, as the relationship between the `cli` layer and stdlib `flag` layer prevents a straightforward solution that works with the current `IsSet` signature.  There have been discussions and experiments with alternate flag parser dependencies, although such a decision is A Big Deal™ given how much functionality is gained by relying on stdlib `flag`.

**Comment by jszwedko** [comment]
Folding this into #294
