### ISSUE TITLE
Reason for flagSet && globalSet to be unexported on Context

### ISSUE THREAD

**Issue by zachgersh** [urfave/cli#228]
Hey All,

Sorry if this is the wrong spot for this question.  Wanted to know why both of theses struct fields are un-exported?  I'd actually like to set some more global flags in a Before but can't do that due to the construction of the Context.  Is this an anti-pattern?

**Comment by jszwedko** [comment]
Hi @zachgersh, the flagsets themselves are not exported because it is meant to be an implementation detail that `flag.FlagSet` is being used under the hood. The contract is with the provided flag types.

The flags are actually parsed before `Before` is called anyway, or did you mean to say that you wanted to populate the values of the flags in the `Before` call?

**Comment by zachgersh** [comment]
@jszwedko Thanks for the reply!  I basically want to look up an initial global flag passed and then set some other global flags based on that.

My example would be:

I have a -t flag that sets a target as `foobar`.  A target is a actually a url that can be made up of url + username + password.  So I would love to look up your target and then set the -url -password and -username global flags.

Could I drop a PR in for a getter / setter that would expose the globalSet (if you want to keep the struct field isolated).

**Comment by jszwedko** [comment]
Gotcha, that is an interesting use case. I think a setter on the context makes sense.

**Comment by jszwedko** [comment]
E.g. `context.Set('url', 'Some value')`. PRs welcome!

**Comment by meatballhat** [comment]
Closing due to the existence of `Context.Set(string, string) error`.  Please yell if you disagree!
