### ISSUE TITLE
Support bool options with `-key value` assignment

### ISSUE THREAD

**Issue by elgs** [urfave/cli#358]
Given the `BoolFlag`  `Name: "enable, e",`, in the command line, `-e=true` can be correctly understood, however, `-e true` seems to be always ignored. There is no such problem for String or Int flags.

**Comment by jszwedko** [comment]
This is actually due to the behavior of the standard library `flag` package that is leveraged heavily internally to handle the parsing.

(from https://golang.org/pkg/flag/)
> Command line flag syntax:
```
-flag
-flag=x
-flag x  // non-boolean flags only
```

I think it would take a bit of rework to support this additional behavior, but I'm open to reviewing a pull request adding it if there is enough demand.

**Comment by lynncyrin** [comment]
Given that this is from last year, I think I'm comfortable closing it 🙂 feel free to re-open / open a new issue / comment in support if there's still interest here!
