### ISSUE TITLE
Options after arguments are ignored

### ISSUE THREAD

**Issue by noffle** [urfave/cli#533]
Consider the following example, which is one of the README examples that has been slightly modified:

```go
package main

import (
	"fmt"
	"os"

	"github.com/urfave/cli"
)

func main() {
	app := cli.NewApp()

	app.Flags = []cli.Flag{
		cli.StringFlag{
			Name:  "lang",
			Value: "english",
			Usage: "language for the greeting",
		},
	}

	app.Action = func(c *cli.Context) error {
		fmt.Println(c.String("lang"))
		return nil
	}

	app.Run(os.Args)
}
```

And the following invocations:

```sh
$ ./cli-test --lang spanish
spanish

$ ./cli-test foo --lang spanish
english
```

In the second invocation, the `lang` option is ignored.

This may have been by design, but it makes the library unable to handle `wget`-like invocations of e.g. `wget http://foo.bar/index.html -o file.html` where the options act like operators on the argument(s).

**Comment by jszwedko** [comment]
Hi @noffle!

Unfortunately this is a limitation of the standard library `flag` library which `cli` uses for flag parsing under the hood. I'd love to be able to address this, but it will require either substantial flag preprocessing or just replacing flag parsing with our own implementation (more likely).

Since this is also captured by https://github.com/urfave/cli/issues/427, I'm going to close this and direct you there for further conversation and updates, but thank you for bringing this up!

**Comment by noffle** [comment]
Thanks @jszwedko for directing me to #427!
