### ISSUE TITLE
Slice Flags & EnvVars attributes

### ISSUE THREAD

**Issue by jrnt30** [urfave/cli#549]
First, thanks for a great project.  Newer to go and really like the well thought out library here and the time that went into it!  It certainly is helpful to get going with. 

---

I see there is a lot of discussion in other threads about the precedence of Default Values, Command Line flags and Environment Variables when it comes to the *SliceFlag attributes. I was hoping to get clarification around my expectations and will take a stab at modifying the behavior if there is consensus around how it should work or will look into updating the documentation to make it explicit how these differ from other types of attributes. 
## Attribute Precedence

**Expected**
- Env Variables would override Default Values 
- Command Line flags would override both Default Values & Command Line Flags

**[Reality](https://github.com/urfave/cli/compare/v2...jrnt30:env-attribute-precedence?expand=1)**
- Env Variables and Command line flags are _appended_ together (defaults are properly ignored but Tests do fail)
- This differs from the relationship of other non-slice flags such as String (test added as well for validation)

| Defaults Provided | Env Variable Configured | Env Variable Present | Command Line Flags | Expected | Actual |
| --- | --- | --- | --- | --- | --- |
| Yes | Yes | Yes | No | Env Variable | Env Variable (Split) |
| Yes | No | No | Yes | Command Line Flags | Command Line Flags |
| No | Yes | Yes | Yes | Command Line Flags | **Command Line Flags AND Env Variable** |
| Yes | Yes | Yes | Yes | Command Line Flags | **Command Line Flags AND Env Variable** |
## Attribute Parsing

**Expected**
- Env Variable & Command Line flags would be parsed the same 

**Reality** 
- Env var files are split on comma
- Command line flags are treated as a single value 

NOTE: This slicing on `,` for env vars vs. command line flags may be intentional, just slightly different than what I expected when looking at the unit tests

**Comment by jszwedko** [comment]
Hi @jrnt30,

Thank you for this well written issue!

The behavior with environment variables splitting on `,` is to facilitate setting multiple values as an environment variable. E.g. `LANGS=english,french,spanish` will get converted to `[]string{"english", "french", "spanish"}`. However, I agree that that behavior differing from what happens when `--langs english,french,spanish` is provided is confusing. To that end, I'm wondering if we should either:

* split the argument values on ","s too (seems like moderately surprising behavior)
* maybe even just drop direct support for environment variables from `Flag`s and take an approach closer to Python's argparse (requiring users to use `os.Getenv(...)` if they want to set a default from the environment (this would be a backwards incompatible change). We could provide helper functions for doing this.
* Something else?

Appending the command line flag values to the default provided value is definitely a bug.

Appending the environment variable values to the flag values also _feels_ like a bug, but I'm curious to get @meatballhat's opinion (as the originator of the parsing from the environment feature).

**Comment by seborama** [comment]
This ought to use the shell syntax for arrays:
(1 2 3)
or var[0]=1 var[1]=2 var[2]=3

Failing that, it is no possible to use comma as a value such as in ("one,two" "three,four")
This is cumbersome to get around when variables are used to provide values (such as in a k8s manifest for instance).

**Comment by dearchap** [comment]
Fixed as part of multiple PRs. Default value now never changes for any flags. 
<html>
<body>


Defaults Provided | Env Variable Configured | Env Variable Present | Command Line Flags | Expected | Actual
-- | -- | -- | -- | -- | --
Yes | Yes | Yes | No | Env Variable | Env Variable (Split)
Yes | No | No | Yes | Command Line Flags | Command Line Flags
No | Yes | Yes | Yes | Command Line Flags | Command Line Flags
Yes | Yes | Yes | Yes | Command Line Flags | Command Line Flags


</body>
</html>
