### ISSUE TITLE
better intergration with pkg/errors

### ISSUE THREAD

**Issue by mh-cbon** [urfave/cli#558]
Hi,

would it be possible to improve a little bit https://github.com/urfave/cli/blob/master/errors.go to have better integration of pkg/errors, thus be able to display a stack trace of the error ?

In my understanding it looks like it needs a type to feed an error rather a string
 `func NewExitError(message string, exitCode int) *ExitError {`

And the `HandleExitCoder` needs a small update to detect formatted errors (https://github.com/pkg/errors/blob/master/errors.go#L126), to apply a `fmt.Printf("%+v", err)` rather than `fmt.Fprintln(ErrWriter, err)`

Or i m doing something wrong when i do `return cli.NewExitError(err.Error(), 1)` ?

**Comment by jszwedko** [comment]
👍  I think that is reasonable and that you've identified the changes that would be required (though I'd like to make them in a backwards compatible manner, so perhaps adding a new method instead of modifying `NewExitError`).

Thank you for the suggestion! Also happy to review a PR.

**Comment by stevvooe** [comment]
I've recently been using this package for some cli work and find this behavior to be fairly annoying. Right now, I have to avoid using `pkg/errors` or I end up with an unnecessary stack trace. Detecting the `fmt.Formatter` interface should really be left to the `fmt` package and surrounding verbs (`+v`, in this case). This behavior is also inconsistent, in practice, due to the fact that it detects the format interface, then issues a different format verb based on presence. If this were another error that implemented format for another verb, it may break 

Either way, I am not sure this was made in a backwards compatible manner. Program output would be different for commands using `pkg/errors` before and after the patch.

Please let me know if you want a PR or if I should file an issue.

**Comment by jszwedko** [comment]
@stevvooe apologies for the delayed response. After further consideration, I tend to agree with you that we generally don't want the end-user to see the stack frames by default (which appears to be what `%+v` gives you).

I will create a separate issue for this. As I don't personally have experience with `pkg/error`, any contributions would be welcome.

**Comment by stevvooe** [comment]
@jszwedko Thanks for taking a peak at this.

Typically, I want to use `errors.Wrap` to create a user-friendly message, then perhaps get the stack trace through some other mechanism, like a hook. We've seen a few PRs (in containerd) working around this by dropping stack data or avoiding the package, which is not what we want either.
