### ISSUE TITLE
idea: cod gen to remove the untyped handler

### ISSUE THREAD

**Issue by gedw99** [urfave/cli#573]
The cmd action handlers are untyped. 
I think goa can be made to code gen all the current boiler plate code.
https://github.com/goadesign/goa/blob/v2/cmd/aliaser/main.go
I say this because the patterns in the CLI are just very consistent, and so a handler with fully strongly typed context can be made for each CLI action.
Its just like another form of RPC; and so why i specifically linked this folder.

**Comment by jszwedko** [comment]
Hi @gedw99,

Apologies for the delay in reviewing this issue.

We modified the type of the `.Action` fields to be `interface{}` as part of https://github.com/urfave/cli/pull/361 in order to facilitate automatically handling errors generated by actions by starting to support handlers returning an `error` in a backwards compatible manner. The original signature is removed in the `v2` branch leaving a [strongly typed `.Action` field](https://github.com/urfave/cli/blob/v2/command.go#L35) which we should hopefully be moving towards releasing in the near future.

I think code generation might end up being overkill for this use case, but I might be missing a simple way that it could be used to support both `.Action` types. Do you mind providing a sample of what the generated code might look like?

Thank you!

**Comment by gedw99** [comment]
thanks @jszwedko 

ok that makes sense thank you.
