### ISSUE TITLE
Bare double dash option

### ISSUE THREAD

**Issue by nshmura** [urfave/cli#596]
Hello,
Thanks for a great package!

I was wondering if it is possible to use bare double-dash option like [this](http://unix.stackexchange.com/a/11382)?
Currently I've making a command line tool that read SQL like language from options:
```
mytool query -- SELECT * FROM Book LIMIT 1
```

And It will be nice if I can get all query string as `c.Args()[0]`:
```
app := cli.NewApp()
app.Commands = []cli.Command{
  // Query
  {
    Name:      "query",
    Action: func(c *cli.Context) error {
      // I wanto set all query string in q variables
      q := c.Args()[0]
      
      return nil
    },
  },
}
```

Thanks

**Comment by jszwedko** [comment]
Hey @nshmura! `--` is supported (due to the underlying support in `flag`) so it `cli` will stop parsing flags when it sees that token. In your example, the remaining tokens should be in `c.Args()` so you can do something like `strings.Join(c.Args(), " ")` to build up the SQL statement.

Hope this helps!

**Comment by nshmura** [comment]
@jszwedko It's great :+1:
Thank for your answer!
