### ISSUE TITLE
Do not show stack trace when using pkg/error

### ISSUE THREAD

**Issue by jszwedko** [urfave/cli#625]
This functionality was added in #560, but https://github.com/urfave/cli/issues/558#issuecomment-281531299 points out that this shows the stack trace to the end-user by default which is generally not desirable.

**Comment by mh-cbon** [comment]
hi,

what if instead the package provides some error handlers in order to let the user decide what to do with the error.

Before that change about `pkg/errors`, there was just no such data available.
Now, there s too much data.
I think, it is only lacking of handling.

Where an error handler could detect that this error is stacktraced, thus appropriately handle it.
An handler which would be bale to read some env to display full stack en dev, partial stack/nostack on production.
To go further a parsing error might return file/line/pos, and an error handler detecting that might print a more appropriate error to the end user, in a generic way.

But, this does not really help current users in the sense that they ll need to appropriately  return typed error to trigger the appropriate display behavior.

That being said, a default error handler might be defined to reproduce old behavior.
Other users would then subscribe the handlers they are interested into to replace that default.

**Comment by mh-cbon** [comment]
To add some example,

3 kind of error output,

> $ myprogram
> wrong arguments
> // I don t want more except maybe help section of the man.

> $ myprogram
> panic(...)
> // I expect to get a trace


> $ myprogram
> wrong syntax at xx ll:pp
> // here you might want to show the source and point the place.

**Comment by lynncyrin** [comment]
Given that this is from last year, I think I'm comfortable closing it 🙂 feel free to re-open / open a new issue / comment in support if there's still interest here!
