### ISSUE TITLE
Json command arguments escape character problem

### ISSUE THREAD

**Issue by i6448038** [urfave/cli#633]
I define a command "delete" which its arguments must be json，and in the code, I get the json string and use `json.Unmarshal()` to get a `map[string]interface{}`，but when I press "xxx delete {"id":“sdfdsfds”}，the application panic an  json.Unmarshal error，because the json arguments I got is "{id:sdfdsfds}", not  "{"id":“sdfdsfds”}". How do I fix this? I don't want to fix this problem with pressing {\"id\":\“sdfdsfds\”}! Is this a bug?

**Comment by phinnaeus** [comment]
Looks to me like you're just running into your shell parsing the quotes. There's nothing the command you're running can do about this because the quotes are removed by the shell before your command is even invoked.

So as you mentioned one way to fix this is to escape the quote characters, another way to fix this is by putting the entire JSON parameter in single quotes.

`xxx delete '{"id":“sdfdsfds”}'`

Example:
```
❯ echo "foo"
foo
❯ echo '"foo"'
"foo"
```

**Comment by i6448038** [comment]
Oh ! yeah ! you are right ! Thank you very much !

**Comment by meatballhat** [comment]
@i6448038 Please holler if you're still having problems :smiley:
