### ISSUE TITLE
Passing negative numbers as arguments?

### ISSUE THREAD

**Issue by akashihi** [urfave/cli#645]
Is there a way to pass negative number and make cli to not to parse it? 

Right now it gives me:
 ./cli command -1
Incorrect Usage: flag provided but not defined: -1

Where `command` is just a command with arguments, which are extracted using context.Args().Get()

**Comment by jszwedko** [comment]
This appears to be because the underlying `flag` used for flag parsing has this behavior:

```
package main

import (
	"flag"
	"fmt"
)

func main() {
	flag.Parse()
	fmt.Println(flag.Args())
}
```

```
go run /tmp/tmp.go -1
flag provided but not defined: -1
Usage of /tmp/go-build523638755/command-line-arguments/_obj/exe/tmp:
exit status 2
```

Unfortunately that means it won't be an easy fix, but I'll mark this to be considered if the `flag` library is removed in lieu of custom flag parsing (which a few other issues would also require).

You can separate the argument with `--` to indicate that all following arguments shouldn't be parsed as flags, like:

```
go run /tmp/tmp.go -- -1
[-1]
```

**Comment by akashihi** [comment]
Thank you, workaround with -- is just fine
