### ISSUE TITLE
Let me parse flags downstream of Command.Action()

### ISSUE THREAD

**Issue by therealplato** [urfave/cli#668]
I have a similar usecase to #269 #663 - I have many existing systems and I want to create a wrapper binary for them. I don't want to rewrite the initialization logic for each system. I'm hoping to just change `package main; func main()` to `package svc1; func Run()`, invoke that function from a `command.Action()`, and be done with it.

However, it appears that after invoking my `cli.v1` binary - even with `SkipFlagParsing: true` - `svc1.Run()` can't successfully invoke `flag.Parse()`. Is this working as designed? 

Repro:
https://gist.github.com/therealplato/8381f6943108149047e60f9a77e48377

**Comment by jszwedko** [comment]
Hi @therealplato,

`flag.Parse()` parses `os.Args[1:]` by default. In your example, this would be `[bar, baz, -c='asdf']`. The `flag` library stops parsing flags when it encounters the first argument thus it will not pick up `-c` as a defined flag since it encounters the argument `bar` first.

Instead of parsing `os.Args[1:]` you should parse the remaining arguments after the command. You can do this with something like:

```
package baz

import (
	"flag"
	"fmt"
)
func Run(c *cli.Context) {
        flagSet := flag.NewFlagSet("my flags", flag.ExitOnError)
        filename := flagSet.String("c", "", "filename of the JSON-based configuration file")
        flagSet.Parse(c.Args())
        fmt.Printf("flag was `%v`", *filename)
}
```

and

```
....
baz.Run(c)
...
```
