### ISSUE TITLE
app.Run(os.Args) should be used with log.Fatal()?

### ISSUE THREAD

**Issue by ahmetb** [urfave/cli#679]
I see `app.Run(os.Args)` all over README.md. But this function returns `error` that's gone unused.

Shouldn't the examples be advocating for `log.Fatal(app.Run(os.Args))` ?

I see that `Run` method actually calls `HandleExitCoder(err)`  and from there `OsExiter(code)` but maybe this is _worth pointing out_ in the README?

It's not immediately clear to me what happens when:
- I return an error that's not `ExitCoder` and have `log.Fatal(app.Run(os.Args))`. (Will I get to log.Fatal, or will it fail anyway even though it's not an ExitCoder?)
- I return an error that's `ExitCoder` but still have `log.Fatal(...)`, is it unnecessary? Or will my error message get printed twice?

**Comment by jszwedko** [comment]
Thanks for noting that @ahmetb, I opened #681 to update the README examples to check for errors.

To answer your questions:

* If you have an error that is not an `ExitCoder` it will bubble back up and be returned by `.Run()`. I wouldn't recommend just doing `log.Fata(app.Run(os.Args)))` since that would exit non-zero and print `<nil>` if there was no error.
* If it satisfies `ExitCoder` `os.Exit()` will be called so execution will terminate before any return value is propagated.

Hope this helps!

**Comment by lynncyrin** [comment]
Given that this is from last year, I think I'm comfortable closing it 🙂 feel free to re-open / open a new issue / comment in support if there's still interest here!
