### ISSUE TITLE
Multiple slice flags cause empty values

### ISSUE THREAD

**Issue by cpurta** [urfave/cli#727]
I am currently using `gopkg.in/urfave/cli.v1` of this for a command line tool that generates a report and emails the results. I am using string slice flags to set the `To`, `CC`, and `BCC` emails and there is some unusual behavior when adding more than one email to the flag.

Example run that works:
```
$ ./report --email-tos to@email.com --email-ccs cc@email.com --email-bbcs bcc1@email.com bcc2@email.com
```

Debugging output:
```
Debug Emails: [to@email.com] [cc@email.com] [bcc1@email.com bcc2@email.com]
```

It appears that only the last flag can have multiple values. When I add multiple emails to the `email-tos` flag the debugging statement shows empty values for all following flag values:

example run that doesn't work:
```
$ ./report --email-tos to1@email.com to2@email.com --email-ccs cc@email.com --email-bbcs bcc1@email.com
```

Debugging output:
```
Debug Emails: [to1@email.com] [] []
```

It appears that any flag following a slice flag with multiple values will not retrieve the values that are received on the command line. If I want to be able to specify multiple emails for one of the flags it must be the last flag on the command like the first example. 

I would expect the behavior of the slice flags to hold all space-separated values until the next flag. I am unsure if there is something that I am missing with using multiple slice flags but any help would be appreciated.

**Comment by mezinski** [comment]
I've circumvented this problem by doing the following

```
{
			Name:    "listjokes",
			Aliases: []string{"jokelist"},
			Usage:   "Lists all of the jokes in the jokes table",
			Flags: []cli.Flag{

				cli.StringFlag{
					Name:  "contributor",
					Value: "",
					Usage: "Name of the contributor to pass into listing to see all their memes",
				},
			},
			Action: func(c2 *cli.Context) error {

				contributorString := ""

				if len(c2.String("contributor")) > 0 {
					arguments := c2.Args()
					contributorString = c2.String("contributor")

					for i := 0; i < len(arguments); i++ {
						contributorString = (contributorString + " " + arguments[i])
					}
				}

				message, ok = ListJokes(contributorString, c2, cmd)

				return nil
			},
		},
```

This allows me to check if they specified the --contributor flag, by checking to see if the length of it is greater than 0 (stating it was passed in), and then appending the following arguments that were found after the --contributor flag, to the contributor flag value, with spacing.


An example of this is within the hipchat application i'm writing

my command used would be "/command listjokes --contributor Adrian Mezinski"

Normally, it would only take in Adrian.

With my addition, it will take Adrian, and check the remaining Args for any other strings, and it will find 
"Mezinski".

It will now loop over all of the remaining arguments(if you have more than one space seperate word/phrase, it will add them all to the flag value aswell)

And for every argument found after the --contributor flag value, it will append it to the value with a " " between them to re-add the space.


I found out this happens because you split the command coming in from the app by spaces, and then it thinks that the one word after the --flag is the value. You have to re-append the floating arguments back to that value afterwards.

Hope this can maybe help you too.

**Comment by tboerger** [comment]
You should provide the flag for every value, but once for a list of values.

**Comment by lynncyrin** [comment]
Marked this one as `help wanted`

**Comment by dearchap** [comment]
The way slice flags works as of v1.22.10 is 

--slice-flag1 value11 --slice-flag1 value12 --slice-flag2 value21 --slice-flag3 value31 --slice-flag3 value32

and so on

The last flag cannot have multiple values are described in issue post.
