### ISSUE TITLE
boolean flags set with '=' but not space

### ISSUE THREAD

**Issue by tcharding** [urfave/cli#740]
When using a `cli.BoolTFlag` type the flag is set to false if the command uses an '=' sign.
```
app --flag=false
```
but if the form `--flag false` is used the value is silently dropped.
```
app --flag false
```
As a developer we know that it is a boolean option (ie a flag) so the behaviour of silently dropping the value is kind of understandable.  But as a user golang typically does not differentiate between the usage of '=' or space for passing command line options.  This behaviour therefore violates the principle of least surprise.

thanks

**Comment by rliebz** [comment]
This is the result of design constraints, and I'm not sure that parsing that way makes more sense than how it works now.

A boolean flag normally does not take arguments. For a boolean flag where the default is false, if the flag is present, the value is set to true. Consider the case where the application takes arguments as well, for a flag with the default value of `false`:

```bash
app --bool-flag foo
```

`--bool-flag` is a boolean flag, so `foo` must therefore be an argument. If the argument becomes `true` by default, isn't changing whether or not an argument passed more surprising? Or even worse, trying to change whether what follows is parsed as an argument based on whether it happens to be `true` or `false`? The `=` syntax is only allowed because it's unambiguous, but really I consider it more surprising that `=` is allowed at all.

The design pattern I use to avoid this situation is to flip the default by using the prefix `no-`.
```bash
# Before
app --foo=false

# After
app --no-foo
```

**Comment by tcharding** [comment]
Thanks for your comment, I agree totally that accepting an `=false` is surprising.  I did try adding negated flags for those that default to true but it seemed to clog up the cli.  Anyways, thanks for your thoughts.
