### ISSUE TITLE
breaking change in struct ordering

### ISSUE THREAD

**Issue by kb-equinox** [urfave/cli#809]
Previously the struct used to be ordered like this:

```
-// StringFlag represents a flag that takes as string value
-type StringFlag struct {
-       Name   string
-       Value  string
-       Usage  string
```

Now it's ordered like this:

```
type StringFlag struct {
    Name        string
    Usage       string
    EnvVar      string
    FilePath    string
    Hidden      bool
```

This means if you had written:

```
x := StringFlag{"one", "two", "three"}
```

and updated the library version, you may have assumed the new field was added at the end, not that the fields had been rearranged.

(I say this because I did exactly that and broke clients that were deployed in the wild.)

In the future I recommend maintaining the struct order and adding new fields at the end, or requiring structs to use named parameters (there are tricks for requiring this).

**Comment by lynncyrin** [comment]
@kb-equinox this all makes sense!

> maintaining the struct order and adding new fields at the end

I'm wondering if there's some easy way to enforce this programmatically 🤔

**Comment by AudriusButkevicius** [comment]
You'd use a builder, or a NewXXX method that gains parameters and breaks at build time

**Comment by amoghrajesh** [comment]
@coilysiren @kb-equinox I am new to OSS and would like to try to contribute to this issue if it is a mere reordering of the struct fields if I understand it correctly.

**Comment by rliebz** [comment]
While it's definitely unfortunate that real world code has had to break because of this change, I'm not sure that the assumption that struct fields will stay in order when new fields are added was ever safe to make. 

From the Go 1 Compatibility Promise:

> Struct literals. For the addition of features in later point releases, it may be necessary to add fields to exported structs in the API. Code that uses unkeyed struct literals (such as pkg.T{3, "x"}) to create values of these types would fail to compile after such a change. However, code that uses keyed literals (pkg.T{A: 3, B: "x"}) will continue to compile after such a change. We will update such data structures in a way that allows keyed struct literals to remain compatible, although unkeyed literals may fail to compile. (There are also more intricate cases involving nested data structures or interfaces, but they have the same resolution.) We therefore recommend that composite literals whose type is defined in a separate package should use the keyed notation. 

Ref: https://golang.org/doc/go1compat

Two things here—

1. The recommendation by the Go authors is to not use unkeyed struct literals for types declared outside of the package. This is sound advice, and would have prevented the issue caused. There is also a vet warning related to this pattern (see: `go tool vet help composites`)
2. The Go standard library does not consider the kind of changes that were made here as part of the compatibility promise, and I don't think it's reasonable to assume that a 3rd party library should be holding itself to higher standards for backward compatibility than the standard library does.

@amoghrajesh I really appreciate the willingness to open up a contribution here. I think the challenges are that at this point, re-ordering the field names would break programs that made the same assumption in the past two years that was made as described in the original issue. 

My recommendation here would actually be to take no action. Happy to discuss further if there's anything I'm missing here.

**Comment by kevinburke** [comment]
One thing you could do is eg

```go
type StringFlag struct {
    _RequireNamedParameters struct{}
    Name        string
    Usage       string
    EnvVar      string
    FilePath    string
    Hidden      bool
}
```

The new field would require all callers to list the parameters instead of adding them implicitly.

**Comment by meatballhat** [comment]
I fear this may be a case of `#wontfix`. Please holler if you feel otherwise and would like to see action taken ❤️
