### ISSUE TITLE
String flag that takes a value does not handle empty string

### ISSUE THREAD

**Issue by dontlaugh** [urfave/cli#908]
I have a program that is called from CI like this

```
cmd --f1 $FLAG1 --f2 $FLAG2
```

I was hoping to be able to rely on both `--f1` and `--f2` being set to empty string `""`, but not use `Required: true`, which results in a non-zero exit code.

But in the above case, `--f1` takes the string `--f2` as a value if the `$FLAG1` env var is not set.

Here is a small reproduction

```go
package main

import (
	"fmt"
	"os"

	"github.com/urfave/cli"
)

func main() {
	app := cli.NewApp()
	flag1 := cli.StringFlag{Name: "f1"}
	flag2 := cli.StringFlag{Name: "f2"}
	app.Flags = []cli.Flag{flag1, flag2}
	app.Action = func(ctx *cli.Context) {
		f1 := ctx.GlobalString("f1")
		f2 := ctx.GlobalString("f2")
		fmt.Println("f1", f1, "f2", f2)
	}
	app.Run(os.Args)
}
```

Run with something like `./repro --f1 $NOEXIST --f2 $NOEXIST`, and you'll see the following output:

```
f1 --f2 f2
```

To me, it was suprising that `--f2` was taken as a value.

**Comment by lynncyrin** [comment]
@dontlaugh from the point of view of the CLI, what you're inputting here is the following literal text =>

```
./repro --f1 --f2
```

When those are both string flags, it's _extremely unclear_ what the desired behavior would be.

So when running the CLI, you would need the eventual CLI input to be something like this =>

```
./repro --f1 "" --f2 ""
```

and **not** =>

```
./repro --f1 $NOEXIST --f2 $NOEXIST
```

☝️ because I can't guarantee that the above input will produce reasonable behavior.

---

Another thing you could do, is something like this (psuedo-code) =>

```
if f1.value == "--f2" {
    f1.value == nil
}
```

---

Either way, the CLI is working as expected in this particular case IMO - so I'm closing this. Feel free to continue replying if you need more assistance!
