### ISSUE TITLE
How do you get the current context?

### ISSUE THREAD

**Issue by rhugga** [urfave/cli#915]
My main challenge right now is the inability to create or obtain a context. I can create a fake app, call app.Run with a slice of arguments but I need the context to be able to actually write my tests. So far I have been unable to create one from scratch or figure out a way to get the context outside of it's methods.

---

_(this issue has been edited by a maintainer)_

**Comment by lynncyrin** [comment]
@rhugga I edited your issue so that it starts with stating the problem you would like to solve.

**Comment by rhugga** [comment]
So you hacked up my issue instead of just answering it? Really? Using spf13/cobra now. Moved to it yesterday, was done integrating and writing tests for it in less than 2 hours.

**Comment by lynncyrin** [comment]
For the sake of anyone dropping into this issue, the text I removed was:

> This is a very challenging library to write tests for. Are there any _good_ examples of writing test, preferable table driven.

It's my professional opinion that this ☝ text made the issue harder to read, and that removing it made the question more likely to be answered.

Maintaining open source projects is volunteer work, and I did my best to help this question get an answer. I didn't answer it directly because I _dont know the answer_, and I have other priorities that govern my life. Petting dogs, texting the girlfriend, cleaning my room, etc etc.

I'm finding the energy here fairly toxic, so I'm locking the issue.
