### ISSUE TITLE
Is there such a function?

### ISSUE THREAD

**Issue by arrowfeng** [urfave/cli#930]
sorry, I have read doc,  but I don't seem to find this function, maybe I read it carelessly.

If I set an option, then other options become unnecessary(the shell will not reminder me type those options if I don't type it). Conversely, if I don't set an option, other options must be set(the shell will reminder me type those options if I don't type it)

**Comment by lynncyrin** [comment]
@arrowfeng I don't understand what you're asking here, can you fill out this issue template?

---

### Prerequisites

* [ ] Are you running the latest v1 or v2 release?
* [ ] Did you check the manual for your release?
* [ ] Are you reporting to the correct repository?
* [ ] Did you perform a Github issue search about this problem?

### Description

[Description of the bug or feature]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

**Comment by arrowfeng** [comment]
### Prerequisites

- [ ]  Are you running the latest v1 or v2 release?
v1
- [ ]  Did you check the manual for your release?
yes
- [ ]  Are you reporting to the correct repository?
yes

- [ ]  Did you perform a Github issue search about this problem?
i have check it.

### Description
Suppose I have a program based on this repository，it has these options: `-a` `-b` `-c` `-f`, and I hope `-f` is mutually exclusive with `-a` `-b` `-c`. That is, if I set `-f`,  so it should not prompt me to set another options. this program work well. If I don't set `-f`, so `-a` and `-b` as well as `-c` should be set simultaneously, or this program don't work.

**Comment by AudriusButkevicius** [comment]
You can check which flags are set yourself, and return errors to the user if mutually exclusive flags are set. There is nothing in the library that will do that for you.

**Comment by arrowfeng** [comment]
> You can check which flags are set yourself, and return errors to the user if mutually exclusive flags are set. There is nothing in the library that will do that for you.

thank you
